/*
 * JKTableWindow.java
 *
 * Created on 3 de noviembre de 2007, 17:04
 */

package newtonpath.ui.widget;

import java.awt.Container;

/**
 * 
 * @author oriol
 */
public class JKInternalWindow extends javax.swing.JInternalFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4867148941849833483L;
	static int openFrameCount = 0;
	static final int xOffset = 30, yOffset = 30;

	// private Container table;

	/** Creates new form JKTableWindow */
	public JKInternalWindow(Container _panel) {
		super("View #" + (++openFrameCount), true, // resizable
				true, // closable
				true, // maximizable
				true);// iconifiable

		initComponents();
		// table=_panel;//new JKTable(_parent);
		// getContentPane().add(table, java.awt.BorderLayout.CENTER);
		if (_panel != null) {
			setContentPane(_panel);
		}
		pack();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed"
	// desc=" Generated Code ">//GEN-BEGIN:initComponents
	private void initComponents() {

		pack();
	}// </editor-fold>//GEN-END:initComponents

	// Variables declaration - do not modify//GEN-BEGIN:variables
	// End of variables declaration//GEN-END:variables

}
